### ISSUE TITLE
Implement password check

### ISSUE THREAD

**Issue by AngeloTadeucci** [AngeloTadeucci/Maple2#221]
Should use a modern encryption like bcrypt.

https://github.com/AngeloTadeucci/Maple2/blob/master/Maple2.Server.World/Service/GlobalService.cs#L21

**Comment by smellilac** [comment]
> Should use a modern encryption like bcrypt.

Hi!

I am ready to do this, but I have a few questions.

The `Account` class does not contain a property for the password, much less its hash, so I am not sure it would be right to delve so deeply into the functionality of your program.

I can add a simple check for the password hash:

```
if (!BCrypt.Net.BCrypt.Verify(request.Password, account.PasswordHash)) {
logger.Warning("Incorrect password for account {AccountId}", account.Id);
return Task.FromResult(new LoginResponse {
Code = LoginResponse.Types.Code.ErrorPassword,
Message = "Incorrect password",
});
}
```

Or go further and add functionality for the password

**Comment by AngeloTadeucci** [comment]
Hey,
Adding just the password check I think would accomplish nothing, so you could go ahead and add the password hash to the Account class.

You can join the discord for help as well
