### ISSUE TITLE
Got Discord banned after world-war project?

### ISSUE THREAD

**Issue by MatthewHinds** [AngeloTadeucci/Maple2#265]
Just checking in. I got banned from the discord over asking if the world-war project was a scam?

**Comment by Zintixx** [comment]
It is a scam. My account got hacked.

**Comment by MatthewHinds** [comment]
Thanks I thought as much. Hope you're able to regain control and not too much damage is done

**Comment by Zintixx** [comment]
This has been resolved now. Apologies for the inconvenience
